import { useRef, Suspense, useMemo } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { Canvas, useFrame } from '@react-three/fiber';
import { Float, Sphere, MeshDistortMaterial, Stars, Text3D, Center } from '@react-three/drei';
import * as THREE from 'three';
import { useStore } from '../store/useStore';
import {
  ArrowForward,
  AutoAwesome,
  TrendingUp,
  Restaurant,
  FitnessCenter,
  Timer,
  EmojiEvents,
} from '@mui/icons-material';

// 3D Floating Orb Component
function FloatingOrb({ position, scale, speed = 1 }: { position: [number, number, number]; scale: number; speed?: number }) {
  const meshRef = useRef<THREE.Mesh>(null);
  
  useFrame((state) => {
    if (meshRef.current) {
      meshRef.current.rotation.x = state.clock.elapsedTime * 0.2 * speed;
      meshRef.current.rotation.y = state.clock.elapsedTime * 0.3 * speed;
    }
  });

  return (
    <Float speed={2} rotationIntensity={0.5} floatIntensity={1}>
      <Sphere ref={meshRef} args={[1, 64, 64]} scale={scale} position={position}>
        <MeshDistortMaterial
          color="#ffffff"
          attach="material"
          distort={0.4}
          speed={2}
          roughness={0.1}
          metalness={0.8}
          opacity={0.15}
          transparent
        />
      </Sphere>
    </Float>
  );
}

// 3D Grid Floor
function GridFloor() {
  return (
    <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -3, 0]}>
      <planeGeometry args={[100, 100, 50, 50]} />
      <meshBasicMaterial color="#ffffff" wireframe opacity={0.03} transparent />
    </mesh>
  );
}

// 3D Scene
function Scene3D() {
  return (
    <>
      <ambientLight intensity={0.5} />
      <pointLight position={[10, 10, 10]} intensity={1} />
      <pointLight position={[-10, -10, -10]} intensity={0.5} color="#ffffff" />
      
      <Stars radius={100} depth={50} count={3000} factor={4} saturation={0} fade speed={1} />
      
      <FloatingOrb position={[-4, 2, -5]} scale={1.5} speed={0.5} />
      <FloatingOrb position={[5, -1, -8]} scale={2} speed={0.7} />
      <FloatingOrb position={[0, 3, -10]} scale={2.5} speed={0.3} />
      <FloatingOrb position={[-6, -2, -6]} scale={1} speed={0.9} />
      <FloatingOrb position={[7, 1, -12]} scale={3} speed={0.4} />
      
      <GridFloor />
    </>
  );
}

const features = [
  {
    icon: Restaurant,
    title: 'AI-Powered Plans',
    description: 'Personalized meal plans generated by advanced AI, tailored to your exact needs.',
  },
  {
    icon: TrendingUp,
    title: 'Real-time Tracking',
    description: 'Track calories, macros, and progress with beautiful visual dashboards.',
  },
  {
    icon: FitnessCenter,
    title: 'Workout Integration',
    description: 'Log workouts and see how exercise affects your daily calorie goals.',
  },
  {
    icon: Timer,
    title: 'Meal Scheduling',
    description: 'Plan your meals ahead with smart scheduling and reminders.',
  },
  {
    icon: AutoAwesome,
    title: 'Smart Suggestions',
    description: 'Get intelligent recipe alternatives with matching nutritional profiles.',
  },
  {
    icon: EmojiEvents,
    title: 'Gamified Progress',
    description: 'Build streaks, earn achievements, and compete on leaderboards.',
  },
];

const stats = [
  { value: '50K+', label: 'Active Users' },
  { value: '2M+', label: 'Meals Logged' },
  { value: '98%', label: 'Success Rate' },
  { value: '4.9', label: 'App Rating' },
];

export default function LandingPage() {
  const navigate = useNavigate();
  const { setOnboarding } = useStore();
  const containerRef = useRef<HTMLDivElement>(null);
  
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start start", "end end"]
  });
  
  const y1 = useTransform(scrollYProgress, [0, 1], [0, -100]);
  const opacity1 = useTransform(scrollYProgress, [0, 0.3], [1, 0]);

  const handleGetStarted = () => {
    setOnboarding(true);
    navigate('/onboarding');
  };

  return (
    <div className="landing" ref={containerRef}>
      {/* 3D Background Canvas */}
      <div className="canvas-container">
        <Canvas camera={{ position: [0, 0, 10], fov: 75 }}>
          <Suspense fallback={null}>
            <Scene3D />
          </Suspense>
        </Canvas>
      </div>

      {/* Hero Section */}
      <section className="hero">
        <motion.nav 
          className="nav"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="logo">
            <div className="logo-mark">S</div>
            <span>SnackTrack</span>
          </div>
          <div className="nav-links">
            <a href="#features">Features</a>
            <a href="#how-it-works">How it Works</a>
            <button className="nav-cta" onClick={handleGetStarted}>
              Get Started
            </button>
          </div>
        </motion.nav>

        <motion.div 
          className="hero-content"
          style={{ y: y1, opacity: opacity1 }}
        >
          <motion.div
            className="badge"
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            <AutoAwesome className="badge-icon" />
            <span>AI-Powered Nutrition</span>
          </motion.div>
          
          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
          >
            Your Diet.
            <br />
            <span className="gradient-text">Reimagined.</span>
          </motion.h1>
          
          <motion.p
            className="hero-subtitle"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
          >
            Personalized meal planning powered by AI. Track your nutrition,
            hit your goals, and transform your health — all in one place.
          </motion.p>

          <motion.div
            className="hero-cta"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.5 }}
          >
            <button className="btn-primary" onClick={handleGetStarted}>
              Start Free Trial
              <ArrowForward className="btn-icon" />
            </button>
            <span className="cta-note">No credit card required</span>
          </motion.div>

          <motion.div
            className="hero-stats"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.7 }}
          >
            {stats.map((stat, i) => (
              <div key={i} className="stat">
                <span className="stat-value">{stat.value}</span>
                <span className="stat-label">{stat.label}</span>
              </div>
            ))}
          </motion.div>
        </motion.div>

        <div className="scroll-indicator">
          <motion.div
            className="scroll-line"
            animate={{ y: [0, 10, 0] }}
            transition={{ duration: 1.5, repeat: Infinity }}
          />
        </div>
      </section>

      {/* Features Section */}
      <section className="features" id="features">
        <div className="container">
          <motion.div
            className="section-header"
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <span className="section-label">Features</span>
            <h2>Everything you need for<br /><span className="gradient-text">optimal nutrition</span></h2>
            <p>Powerful tools designed to make healthy eating effortless and enjoyable.</p>
          </motion.div>

          <div className="features-grid">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <motion.div
                  key={feature.title}
                  className="feature-card glass"
                  initial={{ opacity: 0, y: 40 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: index * 0.1 }}
                  whileHover={{ y: -8, transition: { duration: 0.2 } }}
                >
                  <div className="feature-icon">
                    <Icon />
                  </div>
                  <h3>{feature.title}</h3>
                  <p>{feature.description}</p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="how-it-works" id="how-it-works">
        <div className="container">
          <motion.div
            className="section-header"
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <span className="section-label">How It Works</span>
            <h2>Start in <span className="gradient-text">3 simple steps</span></h2>
          </motion.div>

          <div className="steps">
            {[
              {
                num: '01',
                title: 'Tell us about you',
                desc: 'Share your goals, preferences, dietary restrictions, and health conditions.',
                visual: '🎯'
              },
              {
                num: '02',
                title: 'Get your personalized plan',
                desc: 'AI generates a custom meal plan tailored to your exact nutritional needs.',
                visual: '✨'
              },
              {
                num: '03',
                title: 'Track & achieve',
                desc: 'Log your meals, track progress, and watch yourself transform.',
                visual: '📈'
              },
            ].map((step, index) => (
              <motion.div
                key={step.num}
                className="step glass"
                initial={{ opacity: 0, x: index % 2 === 0 ? -40 : 40 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: index * 0.2 }}
              >
                <div className="step-num">{step.num}</div>
                <div className="step-content">
                  <h3>{step.title}</h3>
                  <p>{step.desc}</p>
                </div>
                <div className="step-visual">{step.visual}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta-section">
        <div className="container">
          <motion.div
            className="cta-card glass-strong"
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <h2>Ready to transform your diet?</h2>
            <p>Join thousands who've already changed their relationship with food.</p>
            <button className="btn-primary large" onClick={handleGetStarted}>
              Get Started Free
              <ArrowForward className="btn-icon" />
            </button>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="container">
          <div className="footer-content">
            <div className="footer-brand">
              <div className="logo-mark">S</div>
              <span>SnackTrack</span>
            </div>
            <p>Making personalized nutrition accessible to everyone.</p>
          </div>
          <div className="footer-bottom">
            <p>© 2025 SnackTrack. All rights reserved.</p>
          </div>
        </div>
      </footer>

      <style>{`
        .landing {
          position: relative;
          min-height: 100vh;
          overflow-x: hidden;
        }

        .canvas-container {
          position: fixed;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          z-index: 0;
          pointer-events: none;
        }

        /* Navigation */
        .nav {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          z-index: 100;
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 1.5rem 3rem;
          background: rgba(0, 0, 0, 0.5);
          backdrop-filter: blur(20px);
          border-bottom: 1px solid rgba(255, 255, 255, 0.05);
        }

        .logo {
          display: flex;
          align-items: center;
          gap: 0.75rem;
        }

        .logo-mark {
          width: 40px;
          height: 40px;
          background: linear-gradient(135deg, #fff 0%, #888 100%);
          border-radius: 12px;
          display: flex;
          align-items: center;
          justify-content: center;
          font-weight: 700;
          font-size: 1.25rem;
          color: #000;
        }

        .logo span {
          font-size: 1.5rem;
          font-weight: 600;
          letter-spacing: -0.02em;
        }

        .nav-links {
          display: flex;
          align-items: center;
          gap: 2.5rem;
        }

        .nav-links a {
          font-size: 0.95rem;
          color: var(--color-gray-400);
          transition: color 0.2s;
        }

        .nav-links a:hover {
          color: var(--color-white);
        }

        .nav-cta {
          padding: 0.75rem 1.5rem;
          background: var(--color-white);
          color: var(--color-black);
          border-radius: var(--radius-full);
          font-weight: 500;
          font-size: 0.95rem;
        }

        .nav-cta:hover {
          background: var(--color-gray-200);
          transform: translateY(-2px);
        }

        /* Hero */
        .hero {
          position: relative;
          z-index: 1;
          min-height: 100vh;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          padding: 8rem 2rem 4rem;
          text-align: center;
        }

        .hero-content {
          max-width: 900px;
          margin: 0 auto;
        }

        .badge {
          display: inline-flex;
          align-items: center;
          gap: 0.5rem;
          padding: 0.5rem 1rem;
          background: rgba(255, 255, 255, 0.05);
          border: 1px solid rgba(255, 255, 255, 0.1);
          border-radius: var(--radius-full);
          font-size: 0.875rem;
          color: var(--color-gray-300);
          margin-bottom: 2rem;
        }

        .badge-icon {
          font-size: 1rem !important;
          color: var(--color-white);
        }

        .hero h1 {
          font-size: clamp(3rem, 8vw, 6rem);
          font-weight: 700;
          line-height: 1.05;
          letter-spacing: -0.03em;
          margin-bottom: 1.5rem;
        }

        .gradient-text {
          background: linear-gradient(135deg, #fff 0%, #666 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
        }

        .hero-subtitle {
          font-size: 1.25rem;
          color: var(--color-gray-400);
          max-width: 600px;
          margin: 0 auto 2.5rem;
          line-height: 1.7;
        }

        .hero-cta {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 1rem;
        }

        .btn-primary {
          display: inline-flex;
          align-items: center;
          gap: 0.75rem;
          padding: 1rem 2rem;
          background: var(--color-white);
          color: var(--color-black);
          border-radius: var(--radius-full);
          font-size: 1.1rem;
          font-weight: 600;
          transition: all 0.3s;
        }

        .btn-primary:hover {
          transform: translateY(-3px);
          box-shadow: 0 10px 40px rgba(255, 255, 255, 0.2);
        }

        .btn-primary.large {
          padding: 1.25rem 2.5rem;
          font-size: 1.2rem;
        }

        .btn-icon {
          font-size: 1.25rem !important;
          transition: transform 0.2s;
        }

        .btn-primary:hover .btn-icon {
          transform: translateX(4px);
        }

        .cta-note {
          font-size: 0.875rem;
          color: var(--color-gray-500);
        }

        .hero-stats {
          display: flex;
          justify-content: center;
          gap: 3rem;
          margin-top: 4rem;
          padding-top: 3rem;
          border-top: 1px solid rgba(255, 255, 255, 0.1);
        }

        .stat {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 0.25rem;
        }

        .stat-value {
          font-size: 2rem;
          font-weight: 700;
          letter-spacing: -0.02em;
        }

        .stat-label {
          font-size: 0.875rem;
          color: var(--color-gray-500);
        }

        .scroll-indicator {
          position: absolute;
          bottom: 2rem;
          left: 50%;
          transform: translateX(-50%);
        }

        .scroll-line {
          width: 2px;
          height: 40px;
          background: linear-gradient(to bottom, rgba(255,255,255,0.5), transparent);
          border-radius: 1px;
        }

        /* Container */
        .container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 0 2rem;
        }

        /* Section Header */
        .section-header {
          text-align: center;
          margin-bottom: 4rem;
        }

        .section-label {
          display: inline-block;
          font-size: 0.875rem;
          font-weight: 500;
          color: var(--color-gray-500);
          text-transform: uppercase;
          letter-spacing: 0.1em;
          margin-bottom: 1rem;
        }

        .section-header h2 {
          font-size: clamp(2rem, 4vw, 3rem);
          margin-bottom: 1rem;
        }

        .section-header p {
          font-size: 1.125rem;
          color: var(--color-gray-400);
          max-width: 600px;
          margin: 0 auto;
        }

        /* Features */
        .features {
          position: relative;
          z-index: 1;
          padding: 8rem 0;
          background: linear-gradient(180deg, transparent 0%, rgba(0,0,0,0.8) 50%, transparent 100%);
        }

        .features-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
          gap: 1.5rem;
        }

        .feature-card {
          padding: 2rem;
          border-radius: var(--radius-xl);
          transition: all 0.3s;
        }

        .feature-icon {
          width: 56px;
          height: 56px;
          background: linear-gradient(135deg, rgba(255,255,255,0.1) 0%, rgba(255,255,255,0.02) 100%);
          border: 1px solid rgba(255, 255, 255, 0.1);
          border-radius: var(--radius-lg);
          display: flex;
          align-items: center;
          justify-content: center;
          margin-bottom: 1.5rem;
        }

        .feature-icon svg {
          font-size: 1.5rem;
          color: var(--color-white);
        }

        .feature-card h3 {
          font-size: 1.25rem;
          font-weight: 600;
          margin-bottom: 0.75rem;
        }

        .feature-card p {
          color: var(--color-gray-400);
          line-height: 1.6;
        }

        /* How It Works */
        .how-it-works {
          position: relative;
          z-index: 1;
          padding: 8rem 0;
        }

        .steps {
          display: flex;
          flex-direction: column;
          gap: 1.5rem;
          max-width: 800px;
          margin: 0 auto;
        }

        .step {
          display: flex;
          align-items: center;
          gap: 2rem;
          padding: 2rem;
          border-radius: var(--radius-xl);
        }

        .step-num {
          font-size: 3rem;
          font-weight: 700;
          color: var(--color-gray-700);
          min-width: 80px;
        }

        .step-content {
          flex: 1;
        }

        .step-content h3 {
          font-size: 1.5rem;
          margin-bottom: 0.5rem;
        }

        .step-content p {
          color: var(--color-gray-400);
        }

        .step-visual {
          font-size: 3rem;
        }

        /* CTA Section */
        .cta-section {
          position: relative;
          z-index: 1;
          padding: 8rem 0;
        }

        .cta-card {
          text-align: center;
          padding: 4rem;
          border-radius: var(--radius-2xl);
        }

        .cta-card h2 {
          font-size: 2.5rem;
          margin-bottom: 1rem;
        }

        .cta-card p {
          font-size: 1.125rem;
          color: var(--color-gray-400);
          margin-bottom: 2rem;
        }

        /* Footer */
        .footer {
          position: relative;
          z-index: 1;
          padding: 3rem 0;
          border-top: 1px solid rgba(255, 255, 255, 0.05);
        }

        .footer-content {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 1rem;
          margin-bottom: 2rem;
        }

        .footer-brand {
          display: flex;
          align-items: center;
          gap: 0.75rem;
        }

        .footer-brand span {
          font-size: 1.25rem;
          font-weight: 600;
        }

        .footer-content p {
          color: var(--color-gray-500);
        }

        .footer-bottom {
          text-align: center;
          padding-top: 1.5rem;
          border-top: 1px solid rgba(255, 255, 255, 0.05);
        }

        .footer-bottom p {
          font-size: 0.875rem;
          color: var(--color-gray-600);
        }

        /* Responsive */
        @media (max-width: 768px) {
          .nav {
            padding: 1rem 1.5rem;
          }

          .nav-links a {
            display: none;
          }

          .hero {
            padding: 6rem 1.5rem 3rem;
          }

          .hero-stats {
            flex-wrap: wrap;
            gap: 2rem;
          }

          .step {
            flex-direction: column;
            text-align: center;
          }

          .step-num {
            font-size: 2rem;
          }

          .cta-card {
            padding: 2rem;
          }
        }
      `}</style>
    </div>
  );
}
